### ISSUE TITLE
p71の "100_run-BaseRecalibrator.sh" で躓いております。

### ISSUE THREAD

**Issue by tempeiikegame** [misshie/ngsdat2#19]
勉強させて頂いております。

p71の "100_run-BaseRecalibrator.sh" を実行すると下記のようなメッセージが出てしまいます。
”Try running IndexFeatureFile on the input.”とのことから、この"IndexFeatureFile"なるものが必要かと思い検索すると
github（https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/tools/IndexFeatureFile.java）に関連しそうな記載がございますが、これ以上進められずにおります。
ご教授いただければ幸いです。
どうぞよろしくお願い申し上げます。

-----------------------------------------------------------------------------------------------------------------------
macbook-pro:DiseaseGenomeMain t**************7$ ./100_run-BaseRecalibrator.sh 
Using GATK jar /Volumes/Transcend/Analysis/ngsdat2-master/DiseaseGenomeMain/gatk-4.1.9.0/gatk-package-4.1.9.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /Volumes/Transcend/Analysis/ngsdat2-master/DiseaseGenomeMain/gatk-4.1.9.0/gatk-package-4.1.9.0-local.jar BaseRecalibrator --input DRR006760.sort.dedup.bam --reference RefHg38/hg38.fasta --output DRR006760.sort.dedup.recaltab.txt --known-sites dbsnp_146.hg38.vcf.gz --known-sites Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
19:15:23.103 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/Volumes/Transcend/Analysis/ngsdat2-master/DiseaseGenomeMain/gatk-4.1.9.0/gatk-package-4.1.9.0-local.jar!/com/intel/gkl/native/libgkl_compression.dylib
Nov 15, 2020 7:15:23 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
19:15:23.924 INFO  BaseRecalibrator - ------------------------------------------------------------
19:15:23.924 INFO  BaseRecalibrator - The Genome Analysis Toolkit (GATK) v4.1.9.0
19:15:23.924 INFO  BaseRecalibrator - For support and documentation go to https://software.broadinstitute.org/gatk/
19:15:23.924 INFO  BaseRecalibrator - Executing as t**************7@MacBook-Pro.local on Mac OS X v10.13.6 x86_64
19:15:23.925 INFO  BaseRecalibrator - Java runtime: Java HotSpot(TM) 64-Bit Server VM v13.0.2+8
19:15:23.925 INFO  BaseRecalibrator - Start Date/Time: 2020年11月15日 19:15:23 JST
19:15:23.925 INFO  BaseRecalibrator - ------------------------------------------------------------
19:15:23.925 INFO  BaseRecalibrator - ------------------------------------------------------------
19:15:23.925 INFO  BaseRecalibrator - HTSJDK Version: 2.23.0
19:15:23.925 INFO  BaseRecalibrator - Picard Version: 2.23.3
19:15:23.926 INFO  BaseRecalibrator - HTSJDK Defaults.COMPRESSION_LEVEL : 2
19:15:23.926 INFO  BaseRecalibrator - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
19:15:23.926 INFO  BaseRecalibrator - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
19:15:23.926 INFO  BaseRecalibrator - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
19:15:23.926 INFO  BaseRecalibrator - Deflater: IntelDeflater
19:15:23.926 INFO  BaseRecalibrator - Inflater: IntelInflater
19:15:23.926 INFO  BaseRecalibrator - GCS max retries/reopens: 20
19:15:23.926 INFO  BaseRecalibrator - Requester pays: disabled
19:15:23.926 INFO  BaseRecalibrator - Initializing engine
19:15:24.096 INFO  FeatureManager - Using codec VCFCodec to read file file:///Volumes/Transcend/Analysis/ngsdat2-master/DiseaseGenomeMain/dbsnp_146.hg38.vcf.gz
19:15:24.105 INFO  BaseRecalibrator - Shutting down engine
[2020年11月15日 19:15:24 JST] org.broadinstitute.hellbender.tools.walkers.bqsr.BaseRecalibrator done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=104857600
***********************************************************************

A USER ERROR has occurred: An index is required but was not found for file /Volumes/Transcend/Analysis/ngsdat2-master/DiseaseGenomeMain/dbsnp_146.hg38.vcf.gz. Support for unindexed block-compressed files has been temporarily disabled. Try running IndexFeatureFile on the input.

***********************************************************************
Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.

**Comment by misshie** [comment]
ご質問いただきありがとうございます。

書籍版では、gatk-4.1.2.0を使って検証しました。エラーメッセージによると、お使いのgatk-4.1.9.0では自動的にvcf.gzファイルに対するインデックスファイルを作成する機能が（将来復活するかもしれないが）一時的にoffになっているようです。

いろいろ対応策があるとおもいますが。まず、現在使用中のgatkを `$ mv gatk-4.1.9.0 zzz_gatk-4.1.9.0`として一旦別名にしておいてから、https://github.com/broadinstitute/gatk/releases/tag/4.1.2.0 からgatk-4.1.2.0をダウンロードしていただき、再チャレンジしていただけないでしょうか？

**Comment by tempeiikegame** [comment]
三嶋先生

お世話になっております。
アドバイスを受けgatk-4.1.2.0をDL致しました。

"100_run-BaseRecalibrator.sh" の実行以前に"./080_download-gatk-bundles.sh"が完了していないようでしたので、
こちらを再度実施し
dbsnp_146.hg38.vcf.gz
dbsnp_146.hg38.vcf.gz.tbi
Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi
を下記のようにDLし直しました。

続けて
./090_prep-reference-index.sh 
./100_run-BaseRecalibrator.sh
./110_run-ApplyBQSR.sh 
を実施いたしましたが、
"/Volumes/Transcend/Analysis/ngsdat2-master/DiseaseGenomeMain/dbsnp_146.hg38.vcf.gz" appears to contain no sequence dictionary.”
と表示されており、”dbsnp_146.hg38.vcf.gz”が不完全なようです。
このまま進めていきますと、
”gunzip -c DRR006760.both.vcf.gz | grep -v ^\# | wc -l”で行数は"0"となってしまいます。

度々申し訳ありませんが、ご助言頂ければ幸いです。

-------------------------------------------------------------------------------------------------
MacBook-Pro:DiseaseGenomeMain tempeiikegame1977$ **./080_download-gatk-bundles.sh** 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 69.173.70.223...
* TCP_NODELAY set
* Connected to ftp.broadinstitute.org (69.173.70.223) port 21 (#0)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0< 220 FTP Server ready.
> USER gsapubftp-anonymous
< 331 Anonymous login ok, send your complete email address as your password
> PASS 
< 230 Anonymous access granted, restrictions apply
> PWD
< 257 "/" is the current directory
* Entry path is '/'
> CWD bundle
* ftp_perform ends with SECONDARY: 0
< 250 CWD command successful
> CWD hg38
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0< 250 CWD command successful
> EPSV
* Connect data stream passively
< 229 Entering Extended Passive Mode (|||60650|)
*   Trying 69.173.70.223...
* TCP_NODELAY set
* Connecting to 69.173.70.223 (69.173.70.223) port 60650
* Connected to ftp.broadinstitute.org (69.173.70.223) port 21 (#0)
> TYPE I
< 200 Type set to I
> SIZE dbsnp_146.hg38.vcf.gz
< 213 3411143311
> RETR dbsnp_146.hg38.vcf.gz
  0 3253M    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0< 150 Opening BINARY mode data connection for dbsnp_146.hg38.vcf.gz (3411143311 bytes)
* Maxdownload = -1
* Getting file with size: 3411143311
{ [14010 bytes data]
 99 3253M   99 3250M    0     0  1620k      0  0:34:15  0:34:14  0:00:01 2242k* Remembering we are in dir "bundle/hg38/"
< 226 Transfer complete
100 3253M  100 3253M    0     0  1620k      0  0:34:15  0:34:15 --:--:-- 2209k
* Connection #0 to host ftp.broadinstitute.org left intact
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 69.173.70.223...
* TCP_NODELAY set
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to ftp.broadinstitute.org (69.173.70.223) port 21 (#0)
< 220 FTP Server ready.
> USER gsapubftp-anonymous
< 331 Anonymous login ok, send your complete email address as your password
> PASS 
< 230 Anonymous access granted, restrictions apply
> PWD
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0< 257 "/" is the current directory
* Entry path is '/'
> CWD bundle
* ftp_perform ends with SECONDARY: 0
< 250 CWD command successful
> CWD hg38
< 250 CWD command successful
> EPSV
* Connect data stream passively
< 229 Entering Extended Passive Mode (|||61570|)
*   Trying 69.173.70.223...
* TCP_NODELAY set
* Connecting to 69.173.70.223 (69.173.70.223) port 61570
* Connected to ftp.broadinstitute.org (69.173.70.223) port 21 (#0)
> TYPE I
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0< 200 Type set to I
> SIZE dbsnp_146.hg38.vcf.gz.tbi
< 213 2466606
> RETR dbsnp_146.hg38.vcf.gz.tbi
< 150 Opening BINARY mode data connection for dbsnp_146.hg38.vcf.gz.tbi (2466606 bytes)
* Maxdownload = -1
* Getting file with size: 2466606
{ [1401 bytes data]
 96 2408k   96 2335k    0     0   325k      0  0:00:07  0:00:07 --:--:--  469k* Remembering we are in dir "bundle/hg38/"
< 226 Transfer complete
100 2408k  100 2408k    0     0   325k      0  0:00:07  0:00:07 --:--:--  561k
* Connection #0 to host ftp.broadinstitute.org left intact
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 69.173.70.223...
* TCP_NODELAY set
* Connected to ftp.broadinstitute.org (69.173.70.223) port 21 (#0)
< 220 FTP Server ready.
> USER gsapubftp-anonymous
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0< 331 Anonymous login ok, send your complete email address as your password
> PASS 
< 230 Anonymous access granted, restrictions apply
> PWD
< 257 "/" is the current directory
* Entry path is '/'
> CWD bundle
* ftp_perform ends with SECONDARY: 0
< 250 CWD command successful
> CWD hg38
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0< 250 CWD command successful
> EPSV
* Connect data stream passively
< 229 Entering Extended Passive Mode (|||65021|)
*   Trying 69.173.70.223...
* TCP_NODELAY set
* Connecting to 69.173.70.223 (69.173.70.223) port 65021
* Connected to ftp.broadinstitute.org (69.173.70.223) port 21 (#0)
> TYPE I
< 200 Type set to I
> SIZE Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
< 213 20685880
> RETR Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
  0 19.7M    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0< 150 Opening BINARY mode data connection for Mills_and_1000G_gold_standard.indels.hg38.vcf.gz (20685880 bytes)
* Maxdownload = -1
* Getting file with size: 20685880
{ [5604 bytes data]
 99 19.7M   99 19.5M    0     0   935k      0  0:00:21  0:00:21 --:--:-- 1108k* Remembering we are in dir "bundle/hg38/"
< 226 Transfer complete
100 19.7M  100 19.7M    0     0   933k      0  0:00:21  0:00:21 --:--:-- 1103k
* Connection #0 to host ftp.broadinstitute.org left intact
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 69.173.70.223...
* TCP_NODELAY set
* Connected to ftp.broadinstitute.org (69.173.70.223) port 21 (#0)
< 220 FTP Server ready.
> USER gsapubftp-anonymous
< 331 Anonymous login ok, send your complete email address as your password
> PASS 
< 230 Anonymous access granted, restrictions apply
> PWD
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0< 257 "/" is the current directory
* Entry path is '/'
> CWD bundle
* ftp_perform ends with SECONDARY: 0
< 250 CWD command successful
> CWD hg38
< 250 CWD command successful
> EPSV
* Connect data stream passively
< 229 Entering Extended Passive Mode (|||63475|)
*   Trying 69.173.70.223...
* TCP_NODELAY set
* Connecting to 69.173.70.223 (69.173.70.223) port 63475
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0* Connected to ftp.broadinstitute.org (69.173.70.223) port 21 (#0)
> TYPE I
< 200 Type set to I
> SIZE Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi
< 213 1500013
> RETR Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi
< 150 Opening BINARY mode data connection for Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi (1500013 bytes)
* Maxdownload = -1
* Getting file with size: 1500013
{ [1401 bytes data]
 35 1464k   35  526k    0     0   141k      0  0:00:10  0:00:03  0:00:07  141k* Remembering we are in dir "bundle/hg38/"
< 226 Transfer complete
100 1464k  100 1464k    0     0   323k      0  0:00:04  0:00:04 --:--:--  323k
* Connection #0 to host ftp.broadinstitute.org left intact
-------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------
MacBook-Pro:DiseaseGenomeMain tempeiikegame1977$ **./090_prep-reference-index.sh** 
INFO	2020-12-12 16:54:26	CreateSequenceDictionary	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    CreateSequenceDictionary -REFERENCE RefHg38/hg38.fasta -OUTPUT RefHg38/hg38.dict
**********


16:54:27.012 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/usr/local/Cellar/picard-tools/2.23.8/libexec/picard.jar!/com/intel/gkl/native/libgkl_compression.dylib
[Sat Dec 12 16:54:27 JST 2020] CreateSequenceDictionary OUTPUT=RefHg38/hg38.dict REFERENCE=RefHg38/hg38.fasta    TRUNCATE_NAMES_AT_WHITESPACE=true NUM_SEQUENCES=2147483647 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Sat Dec 12 16:54:27 JST 2020] Executing as tempeiikegame1977@MacBook-Pro.local on Mac OS X 10.13.6 x86_64; OpenJDK 64-Bit Server VM 15.0.1+9; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.23.8
[Sat Dec 12 16:54:47 JST 2020] picard.sam.CreateSequenceDictionary done. Elapsed time: 0.35 minutes.
Runtime.totalMemory()=92274688
-------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------
MacBook-Pro:DiseaseGenomeMain tempeiikegame1977$ **./100_run-BaseRecalibrator.sh** 
Using GATK jar /Volumes/Transcend/Analysis/ngsdat2-master/DiseaseGenomeMain/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /Volumes/Transcend/Analysis/ngsdat2-master/DiseaseGenomeMain/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar BaseRecalibrator --input DRR006760.sort.dedup.bam --reference RefHg38/hg38.fasta --output DRR006760.sort.dedup.recaltab.txt --known-sites dbsnp_146.hg38.vcf.gz --known-sites Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
17:20:54.717 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/Volumes/Transcend/Analysis/ngsdat2-master/DiseaseGenomeMain/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar!/com/intel/gkl/native/libgkl_compression.dylib
Dec 12, 2020 5:20:56 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
17:20:56.492 INFO  BaseRecalibrator - ------------------------------------------------------------
17:20:56.492 INFO  BaseRecalibrator - The Genome Analysis Toolkit (GATK) v4.1.2.0
17:20:56.493 INFO  BaseRecalibrator - For support and documentation go to https://software.broadinstitute.org/gatk/
17:20:56.493 INFO  BaseRecalibrator - Executing as tempeiikegame1977@MacBook-Pro.local on Mac OS X v10.13.6 x86_64
17:20:56.493 INFO  BaseRecalibrator - Java runtime: Java HotSpot(TM) 64-Bit Server VM v13.0.2+8
17:20:56.493 INFO  BaseRecalibrator - Start Date/Time: 2020年12月12日 17:20:54 JST
17:20:56.493 INFO  BaseRecalibrator - ------------------------------------------------------------
17:20:56.493 INFO  BaseRecalibrator - ------------------------------------------------------------
17:20:56.494 INFO  BaseRecalibrator - HTSJDK Version: 2.19.0
17:20:56.494 INFO  BaseRecalibrator - Picard Version: 2.19.0
17:20:56.495 INFO  BaseRecalibrator - HTSJDK Defaults.COMPRESSION_LEVEL : 2
17:20:56.495 INFO  BaseRecalibrator - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
17:20:56.495 INFO  BaseRecalibrator - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
17:20:56.495 INFO  BaseRecalibrator - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
17:20:56.495 INFO  BaseRecalibrator - Deflater: IntelDeflater
17:20:56.495 INFO  BaseRecalibrator - Inflater: IntelInflater
17:20:56.495 INFO  BaseRecalibrator - GCS max retries/reopens: 20
17:20:56.495 INFO  BaseRecalibrator - Requester pays: disabled
17:20:56.495 INFO  BaseRecalibrator - Initializing engine
17:20:56.706 INFO  FeatureManager - Using codec VCFCodec to read file file:///Volumes/Transcend/Analysis/ngsdat2-master/DiseaseGenomeMain/dbsnp_146.hg38.vcf.gz
17:20:56.860 INFO  FeatureManager - Using codec VCFCodec to read file file:///Volumes/Transcend/Analysis/ngsdat2-master/DiseaseGenomeMain/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
17:20:57.065 WARN  IndexUtils - **Feature file "/Volumes/Transcend/Analysis/ngsdat2-master/DiseaseGenomeMain/dbsnp_146.hg38.vcf.gz" appears to contain no sequence dictionary.** Attempting to retrieve a sequence dictionary from the associated index file
17:20:57.209 INFO  BaseRecalibrator - Done initializing engine
17:20:57.214 INFO  BaseRecalibrationEngine - The covariates being used here: 
17:20:57.214 INFO  BaseRecalibrationEngine - 	ReadGroupCovariate
17:20:57.214 INFO  BaseRecalibrationEngine - 	QualityScoreCovariate
17:20:57.214 INFO  BaseRecalibrationEngine - 	ContextCovariate
17:20:57.214 INFO  BaseRecalibrationEngine - 	CycleCovariate
17:20:57.217 INFO  ProgressMeter - Starting traversal
17:20:57.217 INFO  ProgressMeter -        Current Locus  Elapsed Minutes       Reads Processed     Reads/Minute
17:20:57.220 INFO  BaseRecalibrator - Shutting down engine
[2020年12月12日 17:20:57 JST] org.broadinstitute.hellbender.tools.walkers.bqsr.BaseRecalibrator done. Elapsed time: 0.04 minutes.
Runtime.totalMemory()=167772160
Exception in thread "main" java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class org/broadinstitute/hellbender/transformers/ReadTransformer. Method 'org.broadinstitute.hellbender.utils.read.GATKRead lambda$identity$d67512bf$1(org.broadinstitute.hellbender.utils.read.GATKRead)' at index 65 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at org.broadinstitute.hellbender.transformers.ReadTransformer.identity(ReadTransformer.java:30)
	at org.broadinstitute.hellbender.engine.GATKTool.makePreReadFilterTransformer(GATKTool.java:345)
	at org.broadinstitute.hellbender.engine.GATKTool.getTransformedReadStream(GATKTool.java:374)
	at org.broadinstitute.hellbender.engine.ReadWalker.traverse(ReadWalker.java:93)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1039)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
-------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------
MacBook-Pro:DiseaseGenomeMain tempeiikegame1977$ **./110_run-ApplyBQSR.sh** 
Using GATK jar /Volumes/Transcend/Analysis/ngsdat2-master/DiseaseGenomeMain/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /Volumes/Transcend/Analysis/ngsdat2-master/DiseaseGenomeMain/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar ApplyBQSR --input DRR006760.sort.dedup.bam --output DRR006760.sort.dedup.recal.bam --reference RefHg38/hg38.fasta --bqsr-recal-file DRR006760.sort.dedup.recaltab.txt
17:21:37.452 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/Volumes/Transcend/Analysis/ngsdat2-master/DiseaseGenomeMain/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar!/com/intel/gkl/native/libgkl_compression.dylib
Dec 12, 2020 5:21:38 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
17:21:38.099 INFO  ApplyBQSR - ------------------------------------------------------------
17:21:38.100 INFO  ApplyBQSR - The Genome Analysis Toolkit (GATK) v4.1.2.0
17:21:38.100 INFO  ApplyBQSR - For support and documentation go to https://software.broadinstitute.org/gatk/
17:21:38.100 INFO  ApplyBQSR - Executing as tempeiikegame1977@MacBook-Pro.local on Mac OS X v10.13.6 x86_64
17:21:38.100 INFO  ApplyBQSR - Java runtime: Java HotSpot(TM) 64-Bit Server VM v13.0.2+8
17:21:38.100 INFO  ApplyBQSR - Start Date/Time: 2020年12月12日 17:21:37 JST
17:21:38.100 INFO  ApplyBQSR - ------------------------------------------------------------
17:21:38.100 INFO  ApplyBQSR - ------------------------------------------------------------
17:21:38.101 INFO  ApplyBQSR - HTSJDK Version: 2.19.0
17:21:38.101 INFO  ApplyBQSR - Picard Version: 2.19.0
17:21:38.101 INFO  ApplyBQSR - HTSJDK Defaults.COMPRESSION_LEVEL : 2
17:21:38.101 INFO  ApplyBQSR - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
17:21:38.101 INFO  ApplyBQSR - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
17:21:38.102 INFO  ApplyBQSR - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
17:21:38.102 INFO  ApplyBQSR - Deflater: IntelDeflater
17:21:38.102 INFO  ApplyBQSR - Inflater: IntelInflater
17:21:38.102 INFO  ApplyBQSR - GCS max retries/reopens: 20
17:21:38.102 INFO  ApplyBQSR - Requester pays: disabled
17:21:38.102 INFO  ApplyBQSR - Initializing engine
17:21:38.270 INFO  ApplyBQSR - Done initializing engine
17:21:38.317 INFO  ProgressMeter - Starting traversal
17:21:38.317 INFO  ProgressMeter -        Current Locus  Elapsed Minutes       Reads Processed     Reads/Minute
17:21:38.381 INFO  ApplyBQSR - Shutting down engine
[2020年12月12日 17:21:38 JST] org.broadinstitute.hellbender.tools.walkers.bqsr.ApplyBQSR done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=101711872
Exception in thread "main" java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class org/broadinstitute/hellbender/transformers/ReadTransformer. Method 'org.broadinstitute.hellbender.utils.read.GATKRead lambda$identity$d67512bf$1(org.broadinstitute.hellbender.utils.read.GATKRead)' at index 65 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at org.broadinstitute.hellbender.transformers.ReadTransformer.identity(ReadTransformer.java:30)
	at org.broadinstitute.hellbender.engine.GATKTool.makePreReadFilterTransformer(GATKTool.java:345)
	at org.broadinstitute.hellbender.engine.GATKTool.getTransformedReadStream(GATKTool.java:374)
	at org.broadinstitute.hellbender.engine.ReadWalker.traverse(ReadWalker.java:93)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1039)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
